# permissions for end users to edit trafficroutings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trafficrouting-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rollouts
    app.kubernetes.io/part-of: rollouts
    app.kubernetes.io/managed-by: kustomize
  name: trafficrouting-editor-role
rules:
- apiGroups:
  - rollouts.kruise.io
  resources:
  - trafficroutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollouts.kruise.io
  resources:
  - trafficroutings/status
  verbs:
  - get
